server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:

        - id: employees # 路由标示，必须唯一
          uri: lb://employees # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/employees/** # 路径断言，判断路径是否是以/emp开头，如果是则符合

        - id: department
          uri: lb://department
          predicates:
            - Path=/department/**

        - id: project
          uri: lb://project
          predicates:
            - Path=/project/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:8001' # 域名
            allowedMethods: '*' # 方法
            allowedHeaders: '*' # 头
            allowCredentials: true
            maxAge: 360000